name: Belt Test Build

on:
  push:
    branches:
    - ep21ore

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run build
      shell: cmd
      run: ./build.cmd

    - name: Save Package
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ./BeltTest/CommunityPackage/bin/**
